# Generated by Django 5.1.4 on 2024-12-24 08:36

import django.utils.timezone
from django.db import migrations, models

#Django generates this file automatically based on the models 
# you’ve defined in
#  models.py within the app.
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
